Add location event types
matrix-org/matrix-events-sdk pull request #4
Opened 2022-03-09 10:29 UTC by kerryarchibald

Adds extensible event types `m.ts`, `m.asset` and `m.location` as described by msc3488, originally added to [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/%40types/location.ts)

2022-03-09 10:46 UTC, andybalaam requested changes
It would help me a lot to understand this if we had a test that showed we can serialise and deserialise some of the examples from the spec.  See e.g. https://github.com/matrix-org/matrix-events-sdk/blob/main/test/events/PollStartEvent.test.ts
I think we should be able to accept the fully-migrated events as well as the backwards-compatible ones, so tests for that would be cool too.

2022-03-09 10:46 UTC, andybalaam commented on src/events/location_types.ts
> +    Default = "m.location",
Sorry, I totally misunderstood the spec and I think this should be m.pin as you had it before.

2022-03-09 10:46 UTC, andybalaam commented on src/events/location_types.ts
> +    M_LOCATION_CONTENT &
is this missing `"m.location":` or am I reading it wrong?

2022-03-10 13:23 UTC, andybalaam approved these changes
LGTM

2022-03-10 16:51 UTC, kerryarchibald commented
Closing in favour of https://github.com/matrix-org/matrix-js-sdk/pull/2229

2022-03-10 16:51 UTC, closed without merging